### ISSUE TITLE
Inverted dates

### ISSUE THREAD

**Issue by Protoncek** [bruxy70/Holidays#14]
Is it possible in any way to invert dates? Now dates are in form "2022-02-08",which is US format. I'd like to change that to: "08.02.2022", which is in use in most of Europe.

**Comment by bruxy70** [comment]
I am afraid this is not possible, HA does not have any system setting for date format. There is a time format on user level, but this needs to work on back-end, independent of the isers.
It is an ISO standard format BTW, not a US format. They use Month Day, Year if I am not mistaken.
Also, it is there mainly to work with the blueprint, that is also searching for the date in the ISO format, so it would not work if I'd make it configurable somehow. And I'd like to keep it simple.
Thanks for the suggestion though.

**Comment by Protoncek** [comment]
I was afraid of that, too. So, my only option is to make a custom entity with desired format...

Thanks for explanation!
And, of course, MANY THANKS for this add-on! Very usefull!

**Comment by bruxy70** [comment]
If you are asking to show it on the front end, you do not have to create a custom entity. You can actually read the date in the ISO format, and then display it in whatever format you need.
If you check for example the blueprint for [holiday in week](https://github.com/bruxy70/Garbage-Collection/blob/master/blueprints/holiday_in_week.yaml). There it gets the date, converts it to a timestamp and then does custom formating - there you can put whatever formatting string you want. And you should be able to do that on the front end...
![image](https://user-images.githubusercontent.com/44951610/151707206-1842e3e5-328b-4a8c-ae26-3020cd94419a.png)

**Comment by Protoncek** [comment]
Thanks a lot! I'll look into it and test it.  I didn't come to blueprints yet in HA, but i guess that this would be the perfect time to start and resolve it's "mistery".
