### ISSUE TITLE
Missing holidays

### ISSUE THREAD

**Issue by mikaelhertzman** [bruxy70/Holidays#15]
**Write your question here**

Is there a reason why only half the national holidays (roughly) are visible in the Home Assistant calendar? I've reviewed the entity attributes and all holidays are listed there. First I thought it might have to do with foreign characters (I'm using the Swedish calendar), but I've ruled that out. Please find the list below, I've marked the ones that are displayed in calendar in bold.

I am also filtering out Sundays, but this issue showed before I made that change and regardless if I disable the filter or not.

These days are not listed but might be filtered out because of the Sunday/Söndag-filter
2022-04-17: Påskdagen, Söndag
2022-05-01: Första maj, Söndag
2022-06-05: Pingstdagen, Söndag
2022-12-25: Juldagen, Söndag

**2022-01-01: Nyårsdagen**
**2022-01-06: Trettondedag jul**
2022-04-15: Långfredagen
2022-04-18: Annandag påsk
2022-05-26: Kristi himmelsfärdsdag
**2022-06-06: Sveriges nationaldag**
2022-06-24: Midsommarafton
2022-06-25: Midsommardagen
2022-11-05: Alla helgons dag
**2022-12-24: Julafton**
2022-12-26: Annandag jul
**2022-12-31: Nyårsafton**

**Comment by bruxy70** [comment]
Will check it. The calendar should display the same thing as the attribute. If it does not, then it might be a bug.

**Comment by mikaelhertzman** [comment]
@bruxy70, thank you! Please let me know if you require any additional information or logs! Also, if you need me to I can register a bug once you've looked into it.

**Comment by bruxy70** [comment]
I am getting very weird outputs from the holidays library. Is that normal? Do you have a holiday every Sunday?
(this is just calling the library from a command line in python, nothing to do with my code)
![image](https://user-images.githubusercontent.com/44951610/151711546-f97b989d-a681-4376-af85-be0ffb22e220.png)

**Comment by mikaelhertzman** [comment]
Yes, in Sweden Sundays are counted as "holidays" (don't get me started about this :) ), but they do not have the same status as other national holidays. (This is also the reason for me excluding Sundays with a filter in my configuration.)

Further information can be found in https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/sweden.py:

"Note that holidays falling on a sunday are "lost", it will not be moved to another day to make up for the collision. In Sweden, ALL sundays are considered a holiday. Initialize this class with include_sundays=False to not include sundays as a holiday."

**Important to note** here is that I am missing a lot of holidays that do not occur on Sundays, for example Långfredagen (Good Friday) during Easter.

**Comment by bruxy70** [comment]
Can you try 1.4.1 beta. Would that fix the issue?

**Comment by bruxy70** [comment]
...looks like it got rid of the Sundays, but the missing holidays still do not show. They are in the holidays attribute but do not show in the calendar. Will dig deeper.
Anythow, is it a positive change to keep the exception for Sweden without the Sundays?

**Comment by mikaelhertzman** [comment]
I suspected as much, don't think it has to do with the Sundays but I understand that you need to rule it out. Please let me know if you still need me to try the 1.4.1 Beta!

When it comes to Sundays being excluded I don't know if I can answer for all of Sweden. :) It's interesting that the Swedish python script has the option to exclude and include Sundays when the other countries I checked don't. Perhaps it would be a good idea for me to raise a feature request or question at the Python Holiday Git? I suspect Sunday might be just as much of a holiday in other countries as in Sweden, at least in practice.

Your plugin still allows for filtering out the Sundays from the user end so you should be able to leave it as it was before I think, at least for now.

**Comment by bruxy70** [comment]
Should be fixed in 1.5. Please check and confirm. I left the Sundays out. Thanks.

**Comment by mikaelhertzman** [comment]
That seems to have fixed it, thank you for all your help! And thank you for a great plugin!
