### ISSUE TITLE
US Federal Holidays corrections

### ISSUE THREAD

**Issue by Sudo-Rob** [bruxy70/Holidays#16]
**Describe the bug**

Although some states observe Confederate Memorial Day, it is not a US Federal holiday.  Please refer to the following links:

 [https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/#url=2022](https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/#url=2022)
 [https://en.wikipedia.org/wiki/Confederate_Memorial_Day](https://en.wikipedia.org/wiki/Confederate_Memorial_Day)

In addition, Federal Holidays are always observed on a weekday.  I can't recall any exceptions to this.  There may be presidential inaugurations or other days declared by executive order as a Federal Holiday, but these would only affect Federal Government employees, not municipal garbage collection.  

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

Config Flow for Holidays.

```yaml

```

**Error log/debug information**

```txt
N/A
```

**Screenshots**

This is a snippet from June 22.  Note that both entries are in error.  Juneteenth should be on Monday, and Confederate Day is not a Federal holiday.
![image](https://user-images.githubusercontent.com/56487711/151733923-b2fa3fac-ddcb-412a-89c6-33ace8d8245d.png)

**Version**

Integration version: 
1.4
Home Assistant version: 
core-2021.12.10
supervisor-2021.12.2

**Comment by bruxy70** [comment]
This is what the holidays library gives as an output: 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/44951610/151784538-307d142b-1943-41af-b1f1-5d30fc01e440.png">

I've found an issue that might be related to that: https://github.com/dr-prodigy/python-holidays/issues/594
Is that perhaps the issue? If yes, then this will be sorted once they make a release with the bugfix, and I will make a release referring to the new version. Ok?

**Comment by Sudo-Rob** [comment]
Yes, you can close this.  In the meantime, I need to figure out how to edit the calendar..
