### ISSUE TITLE
Singapore (SG/SGP) missing in country drop down list

### ISSUE THREAD

**Issue by sognen** [bruxy70/Holidays#18]
**Describe the bug**

Singapore does not appear in the country dropdown list. I see a long list of other countries in the mentioned dropdown. Singapore is listed on https://github.com/dr-prodigy/python-holidays.
I am not sure if this makes it a a feature request or a bug report.

Thanks for this integration.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
Integration is configured in gui.

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**

**Version**

Integration version: 
Latest

Home Assistant version: 
Latest

**Comment by OddyAte** [comment]
Hey, I had the same issue but for RO (Romania). I went ahead and with File Editor I modified this file:

/config/custom_components/holidays/const.py

Added "RO" to COUNTRY_CODES list, restarted Home Assistant, changed it in the list and it works fine. You will need to add SG.

**Comment by sognen** [comment]
@OddyAte  Thank you. That worked.
