### ISSUE TITLE
Date Format Customisation

### ISSUE THREAD

**Issue by tamimology** [bruxy70/Holidays#23]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

If there could be a way to customise the date format through the config_flow interface and be included in the sensor's state.
The default is showing as (%Y-%B-%d : Holiday Name)
![image](https://user-images.githubusercontent.com/90429593/153157245-c5ab198a-b008-491a-bc68-26c87840cee2.png)
![image](https://user-images.githubusercontent.com/90429593/153157334-0311244b-1b9d-482c-aa90-86d4bef603c8.png)

### Describe alternatives you've considered

For example, personally, I prefer to have it as (Holiday Name %A %b %-d, %Y), and I had to create a new sensor with customised date format rather than have it configured in UI.
The same applies to "next_date" sensor attribute
![image](https://user-images.githubusercontent.com/90429593/153157413-d0dc3f41-fc6e-4536-b758-7ce4a4d3a0c3.png)

**Comment by bruxy70** [comment]
Thanks for the suggestion, but I will reject that.
The next date atrribute actually returns a value of a type datetime, it is not text. I do not decide how it is shown, this is done by HA. You can obviously format it for your front end, there is no need to create another entity.
The holidays attribute is used by the automation blueprints to search for the date, and they use date in the ISO format. There it is really a list of text values, as I needed to have the holiday next to a date. In a format that is searchable by automation blueprint. Having it different for everyone will not work.
The holidays attribute is a list of values, I do not think anyone would use it as-is. It is too long anyway. I guess the normal way  to show the holidays is through the calendar.
If you want to create a custom solution, you can. But then you can use this list and format them in whatever way you want.  No need to create a new sensor.
