### ISSUE TITLE
Doesn't show up in add integration list after installing

### ISSUE THREAD

**Issue by mclever** [bruxy70/Holidays#26]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Can't add integration after installing and restarting HA, not in list

### Configuration

```JSON
Can't, integration doesn't show up
```

### Debug logs

```shell
Nothing. I see the custom component being found, but nothing else.

We found a custom integration holidays which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by bruxy70** [comment]
Can you uninstall it, check if it is not in the custom_components folder, restart, install again and restart again. I cannot replicate this, it seems to work normally. I have also not heard such issue from anybody else (and I think over 3000 people installed that).

**Comment by mclever** [comment]
Not an issue with your integration. Something related to android companion app cache.

It's working as expected, thank you for sharing!
