### ISSUE TITLE
Country Code for Ireland - IE - not listed in drop-down,

### ISSUE THREAD

**Issue by sotatech** [bruxy70/Holidays#28]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

This is a follow up to this issue: [https://github.com/home-assistant/core/issues/67542](https://github.com/home-assistant/core/issues/67542)  After upgrading to 2022.3.0 I got an error for this integration that the IE country code is invalid.

I also tried your integration and it does not list the IE country code.

### Configuration

```JSON
I cannot configure your integration as it does not have my country code.
```

### Debug logs

```shell
As above.
```

**Comment by bruxy70** [comment]
I see, it is a bug in the holidays library: https://github.com/dr-prodigy/python-holidays/issues/636
Also open bug for Home Assistant core: https://github.com/home-assistant/core/issues/67542
We'll have to wait for the holidays bugfix I suppose. Sorry for that.

**Comment by bruxy70** [comment]
The thing is, the library is used in HA core integration for workday. This dictates the version of the library, so I do not really have a choice.
Are the Irish holidays very different from Northern Ireland? If not, can you tap to these in the meantime?

**Comment by sotatech** [comment]
Well it's a different country so yes they are different but I don't know what the difference is! It's no big deal, but I use the workday integration to manage my heating scheduler. For now I will just change the binary_sensor to a helper entity so I can control it manually.
Thanks for your help 👍

**Comment by Sudo-Rob** [comment]
Is this not the file you need?  Look at line 26.

[https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/ireland.py](https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/ireland.py)
