### ISSUE TITLE
Easter

### ISSUE THREAD

**Issue by ThatGuySM** [bruxy70/Holidays#30]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

How come ester is not listed as a holiday but Christmas is?

**Comment by bruxy70** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/44951610/157115374-2b72cb5d-dd08-4ea2-b528-b006bd7aefe3.png">

Not sure what you configured, but I do see Easter there. 
Anyhow, if you have an issue with with the holidays, you can check with the holidays library. This integration is just a wrapper around it, it does not determine the actual holidays.
