### ISSUE TITLE
Add New Year's Eve as a holiday option

### ISSUE THREAD

**Issue by tkdrob** [bruxy70/Holidays#33]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add New Year's Eve as a holiday option. Some services do not run on that day. Maybe call it New Year's (observed).

### Describe alternatives you've considered

I could try using the exclude blueprint but that currently requires the year and does not move collection to the next available non-holiday

### Additional context

I am in NJ USA

**Comment by bruxy70** [comment]
The integration does not really control what days are listed as holidays and which are not. It merely passes the holidays generated by the standard holidays library. If they have a bug in there, you might want to report it there? Thanks!

**Comment by tkdrob** [comment]
Thanks. I was not exactly sure about that.
