### ISSUE TITLE
No integration in HA 2022.6.4

### ISSUE THREAD

**Issue by ToXinE** [bruxy70/Holidays#35]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Installed the repository from HACS.
Attempted to +Add Integration 
No "Holidays" integration found despite rebooting homeassistant.

### Configuration

```JSON
Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

no holiday integration available so, no device configuration...
```

### Debug logs

```shell
no holiday integration available so, no device configuration...
```

**Comment by ToXinE** [comment]
bump

**Comment by bruxy70** [comment]
I cannot reproduce that I am afraid. The integration generally runs with 2022.6.4 and 2022.6.5. And it is automatically tested with every version, with no issues. And since there are no errors, i do not know why you can't see it. Did it install in the custom_components directory?

**Comment by ToXinE** [comment]
ok, after upgrading to 2022.6.6, it's working now :)
