### ISSUE TITLE
Canadian Holidays 2022 - Next_Holiday is Boxing Day

### ISSUE THREAD

**Issue by CaldwellRoad** [bruxy70/Holidays#40]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Hello,

Just downloaded this from HACS and implemented without issue - thanks for creating this. Configured for Canada (CA) and sub for NS and using the Observed option. This is showing the Next Holiday as Boxing Day as seen in the attributes list:

![image](https://user-images.githubusercontent.com/97407186/204159356-a31dacca-c60f-4a95-9260-707a8ef096f9.png)

It appears that the listing is not showing "Christmas Day" only "Christmas Day (Observed) on 27th" and Boxing Day on 26th, but technically Boxing Day (Observed) should be 27th and Christmas Day (Observed) on the 26th - just a weird falling of Holidays this year for logic I believe. 

Please let me know if you need any additional details or configs (as this is just the default install) as I am new at creating any bug reports and using GitHub.

### Configuration

```JSON
For some reason - I am unable to download the config from my HA instance... I will update when I get that sorted.
```

### Debug logs

```shell
Didn't do any debug logs.
```

**Comment by bruxy70** [comment]
Can you please log this issue with the [Holidays](https://github.com/dr-prodigy/python-holidays) package? This helper is just an interface to this package, it does not calculate any of the holidays. Thanks.

**Comment by CaldwellRoad** [comment]
Sorry about that! I will submit to the proper project.

**Comment by CaldwellRoad** [comment]
It appears to be fixed in latest version v.0.17.2, but Canada specific fixes and improvements in v.0.17 and v.0.16. Does this package need to get the updated version, or is this something manually I can update?
