### ISSUE TITLE
Configuration - default icons swapped (?)

### ISSUE THREAD

**Issue by OldShaterhan** [bruxy70/Holidays#42]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

`mdi:calendar-arrow-right` and `mdi:calendar-check` default icons are swapped either in PL localization file or as default values:

![image](https://user-images.githubusercontent.com/1622866/208636810-73c1b51d-e12a-4649-87eb-ada26af8809c.png)

I'll try to review this inside code later, but just to catch that there's such a issue - reported :)

### Configuration

```JSON
HA 2022.12.7
Holidays 1.9.1
```

### Debug logs

```shell
N/A
```

**Comment by OldShaterhan** [comment]
At first glance it looks that it is set properly in the code? (`config_flow.py` has proper icons set, `const.py` has proper values, I didn't find yet the reason.

**Comment by OldShaterhan** [comment]
Hi @bruxy70 , was it fixed sometime ago? I reviewed code, but I didn't find where the issue is ;)

**Comment by bruxy70** [comment]
https://github.com/bruxy70/Holidays/commit/278a256e2326729059cd9a3f5ed0e68789ec79cd
