### ISSUE TITLE
Can't Exclude Texas Holiday (Juneteenth)

### ISSUE THREAD

**Issue by jasonalsing** [bruxy70/Holidays#49]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

When I add a calendar for US and TX subdivision, if I select 'Emancipation Day In Texas; Juneteenth National Independence Day' to be ignored it is not ignored. All other "Texas" Holidays can be ignored. 

If I choose another subdivision (or none at all) the holiday shows as simply 'Juneteenth National Independence Day' and it successfully can be excluded. Only in the case of the combined holiday does it fail. 

### Configuration

```JSON
Hitting this button does nothing in my installation for some reason. I am merely setting up a Holiday Calendar using US and TX and attempting to exclude the Juneteenth Holiday.
```

### Debug logs

```shell
This error originated from a custom integration.

Logger: custom_components.holidays.calendar
Source: custom_components/holidays/calendar.py:273
Integration: Holidays (documentation, issues)
First occurred: 5:58:34 PM (1 occurrences)
Last logged: 5:58:34 PM

(Texas Test) Holiday not removed ('Emancipation Day In Texas; Juneteenth National Independence Day')
```

**Comment by bruxy70** [comment]
I am updating the dependency on the holidays package to the same as what Home Assistant uses for workday. Not sure if that helps - they had an issue with this but that was fixed in version [0.11.2](https://github.com/dr-prodigy/python-holidays/releases/tag/v0.11.2), and this integration was already using a newer version.

**Comment by jasonalsing** [comment]
This seems to be an issue in the holidays library, at some point they changed the concatenated holiday to  be separated with ; instead of , :

using python3.6/holidays 0.11.3.1:
![image](https://github.com/bruxy70/Holidays/assets/38263272/167e9459-129f-4008-8919-f97a7528a780)

python 3.10/holidays .25 (though HA is using .21 I think):
![image](https://github.com/bruxy70/Holidays/assets/38263272/82422ea0-48f8-4f93-9dc8-c494dabd620c)

**Comment by jasonalsing** [comment]
created issue at the python-holidays github:

https://github.com/dr-prodigy/python-holidays/issues/1281
