### ISSUE TITLE
Can't add the helper, it doesn't appear...

### ISSUE THREAD

**Issue by danielccm** [bruxy70/Holidays#50]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

I had a message after a restart that the integration "Holidays" couldn't be loaded. I uninstalled the helpers, removed the integration, restarted, redownloaded the integration via hacs, restarted home assistant...

and now I can't add the helpers... they don't appear... :-(

### Configuration

```JSON
N/A
```

### Debug logs

```shell
N/A
```

**Comment by ifflanb** [comment]
Yes same for me. I tried downgrading to 1.9.4 and that has the same issue as well.
Should have said I am using latest HA beta release 2023.6.0b4

**Comment by snoppie80** [comment]
yep, same here. Downgrading doesn't solve the problem.

**Comment by Menz01** [comment]
same issue here

**Comment by tm24fan8** [comment]
Indeed.

**Comment by broyuken** [comment]
Same here, running the beta and it says the integration doesn’t exist

**Comment by Protoncek** [comment]
I've got even further: after installing 1.9.5 my HA began to crash regularly every 2-3 minutes. HA console (ssh login) said something about memory overflow error and some funny numbers  -  sadly i didn't wrote them down...

**Comment by bruxy70** [comment]
ls let me know if 1.9.6 release fixes that. Thanks.

**Comment by ifflanb** [comment]
That seems to have fixed it for me. Thanks for the quick turnaround. Much appreciated.

**Comment by Protoncek** [comment]
It works here, too. Many thanks for this really quick fix!

**Comment by snoppie80** [comment]
> yep, same here. Downgrading doesn't solve the problem.

It works again like expected. Many thanks for the quick response.

**Comment by danielccm** [comment]
Fixed! Thanks!
