### ISSUE TITLE
Option to select the preferred Python Holidays language

### ISSUE THREAD

**Issue by spicecode-tech** [bruxy70/Holidays#51]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

Leaving in the French part of Switzerland I got all holidays name in German instead of French.

### Describe the solution you'd like

Python Holidays supports additional languages but we are missing the option to use them.

### Describe alternatives you've considered

Tried to create a custom HA helper to fix but unsuccessfully.

**Comment by bruxy70** [comment]
I think they added that to holidays library from version 0.26. Home Assistant currently uses version 0.21.13, so it does not have the support for localisations yet.
(Home Assistant uses the library for its workday component - so this defines the version, I cannot choose a different version).
So once they update the version, I will add this feature.
