### ISSUE TITLE
Suggestion: recommend updating python-holidays in troubleshooting

### ISSUE THREAD

**Issue by lencioni** [bruxy70/Holidays#58]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

After installing this integration, restarting Home Assistant, and successfully creating the helper, I was unable to get it to show any holidays. I checked my Calendar page in home assistant and it gave me an error message saying that it was unable to fetch any events from the Holidays calendar.

After reading through some issues, I thought that perhaps I needed to install or upgrade the python-holidays package. So I ran these commands:

```sh
sudo apt install python3-pip
pip install --upgrade holidays
```

And then restarted Home Assistant. This fixed the problem for me.

### Describe the solution you'd like

It would be nice to document this in the readme, to help out others who might run into the same issue.

If it is possible for the component to detect this and log some useful error message, that would also be really great, so people don't have to go hunting for the tip in the readme.

Or even better, if this integration could be made compatible with a wider version range, that would be ideal! I have no idea what that would involve though.

### Describe alternatives you've considered

None

### Additional context

Thank you for creating and maintaining this code!

**Comment by bruxy70** [comment]
This is interesting, holidays are used by the workday integration, that is part of core. Also, the requirement is included in the manifest.json (and requirements.txt). So it is installed automatically if you use it in docker, which is most users. And for these the comment in the documenattion woudl be confusing.

**Comment by lencioni** [comment]
FWIW I am using this in docker

**Comment by bruxy70** [comment]
Then installing holidays on your computer makes no difference, it should be installed inside the container.

**Comment by lencioni** [comment]
Hmm, yeah I guess you are right. I wonder why it started working after I did this then...

I also noticed that the `holidays` list took a while to populate, and still wasn't even populated after I had done this and restarted Home Assistant twice, but when I check now I can see all of the holidays listed there. So maybe there was just some initialization that needed to happen?

I was working with the Google calendar integration the other day and remember reading that calendars sync every 15 minutes, so maybe I just needed to wait until after this for the holidays to be populated. Do you think that could be it?
