### ISSUE TITLE
ICS file integration

### ISSUE THREAD

**Issue by tamimology** [bruxy70/Holidays#8]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an optional parameter to integrate the holiday calendar from an ICS file, the file can be local or from website url

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bruxy70** [comment]
This is purely a wrapper around the `holidays` library, I do not plan to bloat it to import holidays from all kind of sources. To do what you'd like to do, you can import the holiday into a google calendar and then have integration for google calendar.
If you want to use it in `garbage_collection`, you can then make and automation to import dates either from the ics (there is a blueprint importing it from txt, so I guess you can change that), or import it from google calendar integrated to HA.
If you do that, you can make the automation into a blueprint and share it for the others (if you can pull it to the garbage collection repository, that would be great.). Thanks!
